version: "3.5"
services:
  db:
    container_name: db
    image: postgres:13.3
    environment:
      - POSTGRES_DB=person_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  flyway:
    image: flyway/flyway:7.12.0
    command: >
      migrate
      -url=jdbc:postgresql://db:5432/person_db
      -schemas=public
      -user=postgres
      -password=postgres
      -connectRetries=5
      -initSql='CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
    volumes:
      - ./migrations/schema:/flyway/sql
    depends_on:
      - db

  app:
    container_name: app
    image: golang:1.16.6
    working_dir: /app
    ports:
      - "50051:50051"
    volumes:
      - .:/app:ro
    command: go run .
    depends_on:
      - db
      - flyway