// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: personsApi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PersonsApiClient is the client API for PersonsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersonsApiClient interface {
	GetPersons(ctx context.Context, in *GetPersonsRequest, opts ...grpc.CallOption) (*GetPersonsResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
}

type personsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPersonsApiClient(cc grpc.ClientConnInterface) PersonsApiClient {
	return &personsApiClient{cc}
}

func (c *personsApiClient) GetPersons(ctx context.Context, in *GetPersonsRequest, opts ...grpc.CallOption) (*GetPersonsResponse, error) {
	out := new(GetPersonsResponse)
	err := c.cc.Invoke(ctx, "/personsApi.PersonsApi/GetPersons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personsApiClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, "/personsApi.PersonsApi/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonsApiServer is the server API for PersonsApi service.
// All implementations must embed UnimplementedPersonsApiServer
// for forward compatibility
type PersonsApiServer interface {
	GetPersons(context.Context, *GetPersonsRequest) (*GetPersonsResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	mustEmbedUnimplementedPersonsApiServer()
}

// UnimplementedPersonsApiServer must be embedded to have forward compatible implementations.
type UnimplementedPersonsApiServer struct {
}

func (UnimplementedPersonsApiServer) GetPersons(context.Context, *GetPersonsRequest) (*GetPersonsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersons not implemented")
}
func (UnimplementedPersonsApiServer) GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedPersonsApiServer) mustEmbedUnimplementedPersonsApiServer() {}

// UnsafePersonsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersonsApiServer will
// result in compilation errors.
type UnsafePersonsApiServer interface {
	mustEmbedUnimplementedPersonsApiServer()
}

func RegisterPersonsApiServer(s grpc.ServiceRegistrar, srv PersonsApiServer) {
	s.RegisterService(&PersonsApi_ServiceDesc, srv)
}

func _PersonsApi_GetPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonsApiServer).GetPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personsApi.PersonsApi/GetPersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonsApiServer).GetPersons(ctx, req.(*GetPersonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonsApi_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonsApiServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personsApi.PersonsApi/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonsApiServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PersonsApi_ServiceDesc is the grpc.ServiceDesc for PersonsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersonsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personsApi.PersonsApi",
	HandlerType: (*PersonsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersons",
			Handler:    _PersonsApi_GetPersons_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _PersonsApi_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "personsApi.proto",
}
